#!/bin/sh

if [ "$1" = "scan" ]
then

docker run -it \
  -v $HOME/.agora/cl:/cl \
  -v $HOME/.agora/el:/el \
  -v $HOME/agoranet/devnet/config/cl:/config \
  -p 3500:3500 -p 4000:4000 -p 13000:13000 -p 12000:12000/udp \
  --name consensus-node --rm \
  bosagora/agora-cl-node:v1.0.3 \
  --datadir=/cl \
  --execution-endpoint=/el/geth.ipc \
  --chain-config-file=/config/chain-config.yaml \
  --config-file=/config/config.yaml \
  --accept-terms-of-use \
  --p2p-host-ip=$(curl -s v4.ident.me) \
  --contract-deployment-block=22 \
  --p2p-allowlist=public \
  --p2p-denylist=private \
  --subscribe-all-subnets=$AGORA_CL_SUBSCRIBE_ALL_SUBNETS \
  --slasher=$AGORA_CL_SLASHER \
  --rpc-max-page-size=500

else

docker run -it \
  -v $HOME/.agora/cl:/cl \
  -v $HOME/.agora/el:/el \
  -v $HOME/agoranet/devnet/config/cl:/config \
  -p 3500:3500 -p 4000:4000 -p 13000:13000 -p 12000:12000/udp \
  --name consensus-node --rm \
  bosagora/agora-cl-node:v1.0.3 \
  --datadir=/cl \
  --execution-endpoint=/el/geth.ipc \
  --chain-config-file=/config/chain-config.yaml \
  --config-file=/config/config.yaml \
  --accept-terms-of-use \
  --p2p-host-ip=$(curl -s v4.ident.me) \
  --contract-deployment-block=22 \
  --p2p-allowlist=public \
  --p2p-denylist=private \
  --subscribe-all-subnets=$AGORA_CL_SUBSCRIBE_ALL_SUBNETS \
  --slasher=$AGORA_CL_SLASHER

fi
