#!/bin/sh

docker run -it \
  -p 4000:4000/udp -p 5000:5000 \
  --name bootnode --rm \
  bosagora/agora-cl-bootnode:v1.0.3 \
  --external-ip $(curl -s v4.ident.me) \
  --fork-version 2F1C0000 \
  --private 5362dcd2dbc637609e58244b304346e0d2bd9787b0d96872b04dd5c76fdfa39c
