#!/bin/sh

rm -rf $HOME/.pooh/cl/*
sudo chmod 664 ~/.pooh/el/geth/jwtsecret
sudo chmod 666 ~/.pooh/el/geth.ipc

mkdir -p $HOME/.pooh
mkdir -p $HOME/.pooh/cl
mkdir -p $HOME/.pooh/cl/config
cp -rf ./poohnet/config/* $HOME/.pooh/cl/config
cp ./poohnet/pooh-deposit-cli/validator_keys/proposer_config.json $HOME/.pooh/cl/config

. ~/.nvm/nvm.sh
nvm use 16
bazel run //beacon-chain --config=release -- \
  --datadir=$HOME/.pooh/cl \
  --execution-endpoint=$HOME/.pooh/el/geth.ipc \
  --chain-config-file=$HOME/.pooh/cl/config/chain-config.yaml \
  --accept-terms-of-use \
  --p2p-host-ip=$(curl -s v4.ident.me) \
  --contract-deployment-block=0 \
  --p2p-allowlist=public \
  --p2p-denylist=private \
  --subscribe-all-subnets=false \
  --slasher=false \
  --rpc-max-page-size=500 \
  --suggested-fee-recipient="0x8B595d325485a0Ca9d41908cAbF265E23C172847" \
  --jwt-secret=$HOME/.pooh/el/geth/jwtsecret \
  --genesis-state=$HOME/.pooh/cl/config/genesis.ssz \
  --contract-deployment-block=0 \
  --bootstrap-node="enr:-MK4QPP1dkann9wZj38DcZR-t8HlNXR026c1xhkO-w92JmpGNizAUvc7J7ihfV2Xx7EbQkw2gwXpkQ2WtgcMANe0YeaGAYsnd9tmh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBlx-CHLxwDAP__________gmlkgnY0gmlwhA-lwymJc2VjcDI1NmsxoQKdy2kTvvwTF-0FZWngp5OeZ-0xxS7fsiKZkcJUvZy6k4hzeW5jbmV0cwCDdGNwgjLIg3VkcIIu4A"
  

